[project]
name = "loke"
version = "0.1.0"
language = "en"
license = "Apache-2.0"

[workspace]
packages = [
  "packages/core",
  "packages/shared",
  "packages/browser",
  "packages/cli",
  "packages/mcp-toke",
  "packages/mcp-broker"
]

[build]
output = "dist/"

[dev]
watch = true
