[site]
name = "loke"
version = "0.2.0"
url = "http://localhost:11430"
language = "en"

[server]
port = 11430
admin = false
corsorigins = "*"

[build]
output = "../../dist/browser/"
minify = true
inline_css = false

[paths]
module_paths = ["../../build/interfaces"]
source_paths = ["../../packages/core/src", "../../packages/shared/src", "../../src/browser", "extensions"]

[store]
backend = "flat"
