[site]
name = "loke"
url = "http://localhost:11430"
language = "en"

[server]
port = 11430
admin = false

[build]
output = "../../dist/browser/"
minify = true
inline_css = false

[store]
backend = "flat"
