#!/usr/bin/env python3
"""Verify the uncommitted toke changes are safe to commit (stories F10.13, X8.5).

Why this exists
---------------
521 `.tk` files sat uncommitted pending the toolchain, and the plan of record was
to commit them as one reviewable mechanical sweep. "Reviewable" is not a property
of a 521-file diff a human will actually read, so it is asserted here instead.

Three findings drove the checks, and each is now a check because each was missed
once by eye:

1. **The licence header had been deleted from 520 files.** A destructive
   repo-wide rewriter did it silently (F10.6, the reason that script was removed).
   Every non-archived `.tk` file in this repository carries a two-line Apache 2.0
   header; committing the sweep as it stood would have stripped the copyright
   notice from the entire codebase. That is an attribution problem, not a style one.

2. **`packages/browser/pages/api/pipeline.tk` is a regression, not a migration.**
   Its working-tree copy drops all nine core imports — the privacy pipeline,
   placeholder restoration, the kill switch, audit logging and policy evaluation —
   and reduces a 207-line handler to 37 lines. The committed version is the good
   one. It must never be committed from the working tree.

3. **Everything else is one substitution.** `=` to `==`, applied by
   `scripts/fix_diagnostics.py` from toke's own byte offsets. Once the headers are
   restored, 200 of 202 changed files contain nothing else, which is a claim worth
   checking mechanically because it is the whole basis for committing them
   unreviewed.

Exit codes
----------
0  the held changes are what they are claimed to be
1  something else is in there; read the report before committing anything
"""

from __future__ import annotations

import argparse
import collections
import re
import subprocess
import sys

# The header is the same notice in two comment syntaxes, because .tk is toke
# source and .tkt is a template. Both lost it to the same rewriter.
LICENCE_MARK = "Copyright 2026 loke contributors"
LICENCE_FIRST_LINE = "// " + LICENCE_MARK          # .tk
LICENCE_SPDX = "// SPDX-License-Identifier: Apache-2.0"
TEMPLATE_FIRST_LINE = "<!-- " + LICENCE_MARK + " -->"   # .tkt

# Must not be committed from the working tree under any option. Not a style
# exception — the working copy is a live privacy regression (NC1.9).
FORBIDDEN = {"packages/browser/pages/api/pipeline.tk"}

# Generated by scripts/build_loke.sh on every build, and tracked, so it diffs
# whenever the generator changes. Exempt from the equality-only rule; its diff
# should be read against the generator's heredoc instead.
GENERATED = {"packages/browser/_serve_main.tk"}


def git(*args: str) -> str:
    return subprocess.run(["git", *args], capture_output=True, text=True).stdout


def normalise_equality(s: str) -> str:
    """Collapse `=` and `==` to one token so an equality-only edit compares equal.

    The negative lookarounds keep `!=`, `<=`, `>=` and `===` out of it, so a
    change from `!=` to `==` is reported rather than silently accepted.
    """
    return re.sub(r"(?<![=!<>])={1,2}(?!=)", "=", s)


def tracked(pattern: str) -> list[str]:
    return [f for f in git("ls-files", pattern).split()
            if not f.startswith("_archived")]


def tracked_tk() -> list[str]:
    return tracked("*.tk")


def check_licence_headers() -> list[str]:
    """Every file that had the header at HEAD must still have it.

    Covers .tk and .tkt. The .tkt case was missed on the first pass and 26 of 29
    templates had lost the notice, which is how this check earned its second
    file type.
    """
    problems = []
    # One pass over HEAD rather than a `git show` per file: git grep -l against the
    # commit lists exactly the files that carried the header when it was written.
    had_header = {
        f[len("HEAD:"):] for f in
        git("grep", "-l", "--fixed-strings", LICENCE_MARK,
            "HEAD", "--", "*.tk", "*.tkt").split("\n")
        if f.startswith("HEAD:") and not f[len("HEAD:"):].startswith("_archived")
    }
    for f in tracked("*.tk") + tracked("*.tkt"):
        if f not in had_header:
            continue  # never had one; not this check's business
        try:
            with open(f, encoding="utf-8") as fh:
                cur = fh.read()
        except FileNotFoundError:
            problems.append(f"{f}: deleted in the working tree but has a licence header at HEAD")
            continue
        first = cur.split("\n", 1)[0]
        if LICENCE_MARK not in first:
            problems.append(f"{f}: licence header removed")
        elif "SPDX-License-Identifier: Apache-2.0" not in cur.split("\n", 3)[1]:
            problems.append(f"{f}: SPDX line removed or altered")
    return problems


def check_forbidden_staged() -> list[str]:
    staged = set(git("diff", "--cached", "--name-only").split())
    return [f"{f}: STAGED, and must not be committed from the working tree"
            for f in sorted(FORBIDDEN & staged)]


def is_licence_header_addition(removed: list[str], added: list[str]) -> bool:
    """A diff that only puts the Apache header on a file that lacked it.

    Allowed as its own category rather than lumped in with the equality sweep,
    because the two are different kinds of change and a reviewer should be told
    which one a file carries. Adding attribution is never the thing to defer.
    """
    if removed:
        return False
    body = [ln for ln in added if ln.strip()]
    return body == [LICENCE_FIRST_LINE, LICENCE_SPDX]


def check_equality_only() -> tuple[list[str], int, int, int]:
    diff = git("diff", "-U0", "--", "*.tk")
    cur = None
    removed: dict[str, list[str]] = collections.defaultdict(list)
    added: dict[str, list[str]] = collections.defaultdict(list)
    for line in diff.split("\n"):
        if line.startswith("+++ b/"):
            cur = line[6:]
        elif line.startswith("-") and not line.startswith("---"):
            removed[cur].append(line[1:])
        elif line.startswith("+") and not line.startswith("+++"):
            added[cur].append(line[1:])

    changed = [c for c in sorted(set(removed) | set(added)) if c]
    problems = []
    clean = 0
    headers_added = 0
    for f in changed:
        if f in FORBIDDEN or f in GENERATED:
            continue
        r, a = removed[f], added[f]
        if is_licence_header_addition(r, a):
            headers_added += 1
            continue
        if len(r) != len(a):
            problems.append(f"{f}: line count differs (-{len(r)} +{len(a)}), so this is "
                            "not a substitution")
            continue
        bad = None
        for x, y in zip(r, a):
            if normalise_equality(x) != normalise_equality(y):
                bad = (x.strip(), y.strip())
                break
        if bad:
            problems.append(f"{f}: change is not equality-only\n"
                            f"      - {bad[0][:110]}\n      + {bad[1][:110]}")
        else:
            clean += 1
    return problems, len(changed), clean, headers_added


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--quiet", action="store_true", help="only report problems")
    args = ap.parse_args()

    licence = check_licence_headers()
    forbidden = check_forbidden_staged()
    equality, n_changed, n_clean, n_headers = check_equality_only()

    if not args.quiet:
        print(f"tracked non-archived .tk files: {len(tracked_tk())}")
        print(f"changed in the working tree:     {n_changed}")
        print(f"  equality-only:                 {n_clean}")
        print(f"  licence header added:          {n_headers}")
        print(f"  excluded by policy:            {len(FORBIDDEN)} forbidden, "
              f"{len(GENERATED)} generated")

    ok = True
    if licence:
        ok = False
        print(f"\nLICENCE HEADERS — {len(licence)} file(s) lost the Apache 2.0 header:",
              file=sys.stderr)
        for p in licence[:10]:
            print(f"  {p}", file=sys.stderr)
        if len(licence) > 10:
            print(f"  ... and {len(licence) - 10} more", file=sys.stderr)
        print("  A repo-wide rewriter did this once before (F10.6). Restore the header;"
              "\n  do not commit its removal.", file=sys.stderr)

    if forbidden:
        ok = False
        print("\nFORBIDDEN FILE STAGED:", file=sys.stderr)
        for p in forbidden:
            print(f"  {p}", file=sys.stderr)
        print("  The working copy of pipeline.tk drops all nine core imports and is a"
              "\n  live privacy regression (NC1.9). Unstage it.", file=sys.stderr)

    if equality:
        ok = False
        print(f"\nNOT A MECHANICAL SWEEP — {len(equality)} file(s) carry other changes:",
              file=sys.stderr)
        for p in equality[:10]:
            print(f"  {p}", file=sys.stderr)
        if len(equality) > 10:
            print(f"  ... and {len(equality) - 10} more", file=sys.stderr)
        print("  Commit these separately with their own reason. The argument for"
              "\n  committing the sweep unreviewed is that it is one substitution.",
              file=sys.stderr)

    if ok and not args.quiet:
        print("\nOK — the held changes are a licence-header-intact, equality-only sweep,")
        print("and the forbidden file is not staged. Safe to commit under F10.13.")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
