[project]
name = "moke"
version = "0.1.0"

[site]
name = "moke"
url = "http://localhost:11432"
language = "en"

[server]
port = 11432
admin = false

[paths]
static = "packages/moke/static"
pages = "packages/moke/pages"
extensions = "packages/moke/extensions/core.tk"

[build]
output = "../../dist/moke/"
minify = true
inline_css = false

[store]
backend = "flat"

[dependencies]
loke_core = { path = "../core" }
